### ISSUE TITLE
Error when adding as custom repository in HACS

### ISSUE THREAD

**Issue by ithinkido** [floris-b/lms_tts_notify#12]
When trying to install by adding as a custom repository , there is an error warning of failing compliance . 

![image](https://user-images.githubusercontent.com/52834821/197081262-7fc45880-dc0f-4a69-aebb-d922b66f9935.png)

```<Plugin floris-b/lms_tts_notify> Repository structure for v0.3.14 is not compliant```

This is a HA supervised ( Home Assistant 2022.10.4
and 
HACS v. (Integration version:	1.28.2)

**Comment by floris-b** [comment]
https://github.com/floris-b/lms_tts_notify/commit/7798a6a3aab5a858f676de2db6435390eccfd54e
