### ISSUE TITLE
Save & restore playlist even when not playing?

### ISSUE THREAD

**Issue by karols-lab** [floris-b/lms_tts_notify#13]
Hi, would it be hard to implement a change to save & restore playlist even if at the moment of announcement the player is stopped/paused?

Right now it the player is playing, the whole process goes well. But if it's not playing and has a playlist defined, it gets cleared out and not restored.

**Comment by floris-b** [comment]
The player needs to be on or playing to retrieve the playlist. 
If I remember correct: if you turn on the player the current playlist starts playing and I opted against that

**Comment by magicus** [comment]
That's too bad. :-( I just discovered this wonderful plugin, but that limitation basically makes it useless. :-(

Is this a limitation in the LMS API? Michael Herger is doing some active development of Lyrion (LMS) these days, maybe it is possible to get changes in the API which will allow this.
