### ISSUE TITLE
Add language and cache

### ISSUE THREAD

**Issue by milansim** [floris-b/lms_tts_notify#14]
Your addon works like a charm when permission on folder is set
However, I really miss language option (for non english speakers) and cache (usefull when HA is offline)

**Comment by floris-b** [comment]
This integration does not need internet access, it does use a text to speech integration that may use it. As far as I know text to speech integrations do use cache
The language of the notify message is set in the text to speech integration, I have no plans to set the language in the notify message

**Comment by milansim** [comment]
It should not be a great revamp of your code but okey, I understand
Thanks on fast reply
