### ISSUE TITLE
Setting multiple players not possible when adding action in the visual editor 

### ISSUE THREAD

**Issue by eremem** [floris-b/lms_tts_notify#17]
Thank you for this great integration.

I'm able to play messages on each of my players separately. However, when I set an action to address all of them at once, in the visual editor this is not possible because only one entity can be selected.

I know that when editing automation in the HA UI, I can use the embedded yaml editor for the action and manually define a list of player IDs for `entity_id` like this:
```
entity_id:
    - media_player.player01
    - media_player.player02
```
This works, but when I edit the automation again, it opens in the visual editor and the above list is reduced to the first item. Quite annoying as it silently modifies the automation:/

Would it be possible to somehow change the definition for action's entity_id property in the integration, so that multiple players could be selected?

**Comment by floris-b** [comment]
I use [notify groups](https://www.home-assistant.io/integrations/group/#notify-groups)

**Comment by eremem** [comment]
Sorry to nag, but I'm quite new to the HA and not sure what you mean. Is the inability to select multiple players a bug in the HA or you use some other approach to achieve what I'm not able to? I'm using the latest version of HA, by the way.
