### ISSUE TITLE
playlist cleared after notify, if player paused/idle

### ISSUE THREAD

**Issue by kct-networx** [floris-b/lms_tts_notify#20]
is it possible to not clear the playlist of a player/group if player/group is paused/idle?

i've tried to edit __init__.py by adding 
`self.restore_playlist(player)`
below line 187, but that didn't fix it.

any ideas?

BR,
Markus

**Comment by floris-b** [comment]
try changing the lines 173 and 181 at the end:  
`== "playing"`
to
`in [ "playing" , "idle" , "paused" ] `

**Comment by kct-networx** [comment]
thank you for your fast response!
your suggested changes are working.
Unfortunately the issue is now, that thee idled/paused playlist starts playing after the end of the notification.
i guess, the state of the player needs to handled in addition, somewhere else...

**Comment by floris-b** [comment]
That's why I opted against it. If you restore the playlist it auto starts playing
If I remember correct: if you send a pause after restoring the playlist there is a brief moment it still plays

**Comment by kct-networx** [comment]
ah, ok. Understand.
I just digged into it, because my son uses pause for his audiobooks to continue later.

So i guess this is an squeezebox/server issue, right?
