### ISSUE TITLE
volume increased randomly

### ISSUE THREAD

**Issue by Hoppaz** [floris-b/lms_tts_notify#23]
Hi, I'm using version 0.3.16 of the plugin and volume gets increased on the devices randomly.

My config sniplet looks like this:
`notify:
    - platform: lms_tts_notify
      name: kueche
      tts_service: tts.google_say
      media_player: media_player.kueche
      device_group: group.all_persons
      alert_sound: Dingdong
      volume: 0.8
    - platform: lms_tts_notify
      name: werkstatt
      tts_service: tts.google_say
      media_player: media_player.werkstatt
      device_group: group.all_persons
      alert_sound: Dingdong
      volume: 0.8
    - platform: lms_tts_notify
      name: bad_oben
      tts_service: tts.google_say
      media_player: media_player.bad_oben
      device_group: group.all_persons
      alert_sound: Dingdong
      volume: 0.8`

Any idea how to debug it to get rid of the problem?

**Comment by Hoppaz** [comment]
I did changed logging of some objects to debug (in LMS) and tried to analyze. I've seen the switch as alarm but was not able to get an idea what is causing it. Afterwards I've set it back to INFO. Since then the problem disapeared. I have no idea why... Closing ticket...

**Comment by floris-b** [comment]
Sometimes after playing the notify message it does not restore the volume set before the notify message
I have not looked into it because it seldom occurs
