### ISSUE TITLE
Message plays and interrupts track playing on a client, but when finished, the track does not resume

### ISSUE THREAD

**Issue by dmshimself** [floris-b/lms_tts_notify#3]
I'm using this with HA 2021.11.1 and installed via HACS.  The LMS server is 8.3.0.  With a track playing on a client, I send a TTS using the "LMS TTS Notify: Say an TTS message to a LMS player" service and this plays just fine, but the track does not resume.  Is there a way to let this happen?

**Comment by floris-b** [comment]
check in LMS if you can save and restore playlists

**Comment by dmshimself** [comment]
Aha!  I've added a suitable folder in Basic Settings/Playlist Folder as 
it was blank by default and all is now well.  Many thanks for the very 
prompt reply

**Comment by zarss** [comment]
Hi. I have tried several times, but no luck so far. I have playlist "Default" witch plays online radio station. Then the notification is played and after that LMS playlist is empty. What I am doing wrong? Thank you.
