### ISSUE TITLE
Glich TTS

### ISSUE THREAD

**Issue by urtaevS** [floris-b/lms_tts_notify#9]
I have some glich in sound. I can't explain this sound... Like stop speaking for a bit after every letter. I got this trouble for all time when i trying to send TTS to LMS devices.
I have 3 andriod device with SbPlayer Installed and two LMS server. All of them have this bug(

**Comment by floris-b** [comment]
strange issue, but if you have the issue in HA when playing a TTS message it has nothing to do with this integration
Try the latest version of LMS server and or an other type of [LMS player](https://sourceforge.net/projects/lmsclients/files/squeezeplay/windows/SqueezePlay-setup-8.0.1r1382.exe/download):
